<a href="https://colab.research.google.com/github/anajuliamelo14/Front-End-Desafios/blob/main/desafio2_machinelearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import tensorflow as tf


In [65]:
import pandas as pd


In [48]:
DataFrame = pd.read_csv('https://raw.githubusercontent.com/sharmaroshan/Zoo-Dataset/refs/heads/master/zoo.csv')

In [49]:
DataFrame_enum = pd.get_dummies(DataFrame)
DataFrame_enum

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  ...  animal_name_tuatara  animal_name_tuna  \
0           1         1  ...                False             False   
1           1         1  ...                False             False   
2           1         0  ...                False             False   
3           1         1  ...                False             False   
4           1         1  ...                False             False   
..        ...       ...  ...                  ...               ...   
96          1         1  ...                False             False   
97          0         1  ...                False             False   
98          1         1  ...                False             False   
99          0         1  ...                False             False   
100         1         1  ...                False             False   

     animal_name_vampire  animal_name_vole  animal_name_vulture  \
0                  False             False                False   
1                  False             False                False   
2                  False             False                False   
3                  False             False                False   
4                  False             False                False   
..                   ...               ...                  ...   
96                 False             False                False   
97                 False             False                False   
98                 False             False                False   
99                 False             False                False   
100                False             False                False   

     animal_name_wallaby  animal_name_wasp  animal_name_wolf  \
0                  False             False             False   
1                  False             False             False   
2                  False             False             False   
3                  False             False             False   
4                  False             False             False   
..                   ...               ...               ...   
96                  True             False             False   
97                 False              True             False   
98                 False             False              True   
99                 False             False             False   
100                False             False             False   

     animal_name_worm  animal_name_wren  
0               False             False  
1               False             False  
2               False             False  
3               False             False  
4               False             False  
..                ...               ...  
96              False             False  
97              False             False  
98              False             False  
99               True             False  
100             False              True  

[101 rows x 117 columns]

In [66]:
dados = DataFrame_enum.drop(columns=['class_type'])
alvo = DataFrame_enum['class_type']

In [67]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(dados, alvo, test_size=0.10, random_state=42)

In [69]:
model = tf.keras.models.Sequential([

  tf.keras.layers.Dense(70, activation=tf.nn.relu),
  tf.keras.layers.Dense(40, activation=tf.nn.relu),
  tf.keras.layers.Dense(8)
])

In [70]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [71]:

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')


y_train = y_train.astype('float32')
y_test = y_test.astype('float32')

model.fit(x_train, y_train, epochs=50)

Epoch 1/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.3196 - loss: 8.6247
Epoch 2/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3552 - loss: 5.1473 
Epoch 3/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3898 - loss: 3.4684 
Epoch 4/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4253 - loss: 3.4290 
Epoch 5/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5646 - loss: 3.0278 
Epoch 6/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6721 - loss: 2.9943 
Epoch 7/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6230 - loss: 2.7694 
Epoch 8/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6386 - loss: 2.5312 
Epoch 9/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6676 - loss: 2.6995 
Epoch 10/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6576 - loss: 2.5453 
Epoch 11/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7082 - loss: 1.9004 
Epoch 12/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8007 - loss: 1.4921 
Ep

In [72]:
model.evaluate(x_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 1.0000 - loss: 0.1901


[0.19009503722190857, 1.0]

In [61]:
dados.size

11716

In [73]:
import numpy as np
from sklearn.metrics import confusion_matrix

previsoes_prob = model.predict(x_test)
previsoes = np.argmax(previsoes_prob, axis=1)
matrix = confusion_matrix(y_test, previsoes)

print(matrix)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
[[9 0 0]
 [0 1 0]
 [0 0 1]]
